### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by developandplay**
As mentioned in #138
A lot of other github projects have this and it saves a few seconds that would be spent on looking at `CONTRIBUTING.md`.
If developers are not satisfied with the templates they can just press the "Open a blank issue" link.
image

All information is taken from [CONTRIBUTING.md](https://github.com/black-parrot/black-parrot/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dpetrisko** [comment]
Thanks! Looks good to me. Is there anything I have to link to do for these templates in GitHub? Unfamiliar with the process

Any thoughts @taylor-bsg ?

**Comment by dpetrisko** [comment]
Looks like templates are looked at from the default branch only: https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates so I changed the base to master

**Comment by developandplay** [comment]
Yep this should work automatically once merged into master.

**Comment by dpetrisko** [comment]
It looks like they should be in an .github/ISSUE_TEMPLATE/ folder though

**Comment by developandplay** [comment]
True...Thanks for catching that one.

**Comment by dpetrisko** [comment]
Can you select allow edits from maintainers? I might touch up the descriptions a bit before merging: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by developandplay** [comment]
I think it should be enabled already.
image
Did you try editing it?

**Comment by dpetrisko** [comment]
Oh, it doesn't let you edit if you're messing with files not in the PR, interesting.

@taylor-bsg I set up a demo repo to show the changes here, check it out: https://github.com/dpetrisko/test-repo

**Comment by black-parrot** [comment]
Thanks for the contribution!

**Pull request merged**
