### PR TITLE
Add instructions for build on docker

### PR DESCRIPTION
**Pull request by mpatnode**
Wayne is currently testing this for me.

### CODE REVIEW

**Comment by dpetrisko** [comment]
Thanks for the PR! A few questions:

- What here is Mac specific? The exact docker command? Can we make this platform agnostic, assuming the user has docker installed
- This should work for tire kick, but we'll need more dependencies for doing useful things, like compiling programs.  We could have 2 docker images, but I think just having the more complete image is better, since users will probably want to run the tire kick, see it pass, and then move on to the next steps.  What do you think?

**Comment by mpatnode** [comment]
- I'm not sure there's much value outside of a Mac, unless folks are seeing other Linux environments where the build is failing.   I didn't install any special versions of anything, just the standard ubuntu components.   Personally, I did all the work inside a WSL container on Windows (actually ran Docker inside of WSL!) 

- Ah, let me try some deeper exploration and see what else is missing.

**Comment by dpetrisko** [comment]
>Personally, I did all the work inside a WSL container on Windows (actually ran Docker inside of WSL!)

That's awesome! 

> I'm not sure there's much value outside of a Mac, unless folks are seeing other Linux environments where the build is failing.

The use case I ran into a lot in university is with systems that you don't have full control over (campus compute clusters, ECE lab computers, research group servers, etc)

**Comment by taylor-bsg** [comment]
Welcome Mike!

**Comment by mpatnode** [comment]
So I've tested this on my Mac, and it seems to be working (still building after 4 hours).

**Comment by taylor-bsg** [comment]
Nice — are you running with any parallel threads on multicore? That is a
long time to wait but we do tend to run with a lot of cores and threads.
Apparently can you rebuild gcc in 30 seconds on a 72-core machine..

**Comment by mpatnode** [comment]
Hmm...  didn't try the parallel build.   Let me look into the Docker CPU allocation.

**Comment by mpatnode** [comment]
"make -j" definitely helps.   Think this is ready to go.

**Comment by dpetrisko** [comment]
Thanks!

**Pull request merged**
