### PR TITLE
Updating submodules and adding timing loop check to DC

### PR DESCRIPTION
**Pull request by dpetrisko**
I updated spike to latest + our changes. Most everything works, except for the spike monitor causes the run to hang.  I disabled it since we're not planning on using it right now, but we should probably raise an issue about it.

The timing loop check I think will be very valuable.  This goes through FreePDK45 elaboration and mapping and checks for timing loops.  This should prevent us from inserting timing loops in RTL and then discovering them months later during tapeout

### CODE REVIEW

**Comment by farzamgl** [comment]
@dpetrisko can you rebase our old commits on top of the new Spike changes?
So we can keep track of them? Right now I can't figure out which BP changes are on that branch.

**Comment by dpetrisko** [comment]
Unfortunately, no.  That will break the build for every branch's submodule.

What I do is:

```
git checkout blackparrot_mods
git diff origin/master
```

Works pretty well, since the diff is small

**Comment by farzamgl** [comment]
> Unfortunately, no. That will break the build for every branch's submodule.
> 
> What I do is:
> 
> ```
> git checkout blackparrot_mods
> git diff origin/master
> ```
> 
> Works pretty well, since the diff is small

What's the last merge commit? Is that all the new changes on the origin repo since we last forked?

**Comment by dpetrisko** [comment]
Yeah it’s just merge upstream/master

**Comment by dpetrisko** [comment]
@stdavids Btw, take a look at this timing loop check.  It's pretty nifty, takes less than 5 minutes total because it's checking post-elab.  Uses FreePDK45 for the target library

**Comment by dpetrisko** [comment]
Anything blocking this?

**Pull request merged**
