### PR TITLE
Matching dram_clock_period_in_ps_p to the core clock

### PR DESCRIPTION
**Pull request by stdavids**

### CODE REVIEW

**Comment by dpetrisko** [comment]
Can you add this to the bp_processor testbench, too?

**Comment by dpetrisko** [comment]
Oh, also: BP sim clk needs to be set here in test_bp.cpp for Verilator.  test_bp.v is only used for VCS runs.

https://github.com/black-parrot/black-parrot/blob/uw_ee477_pparrot_wi20/bp_top/test/tb/bp_softcore/test_bp.cpp

**Comment by dpetrisko** [comment]
Fixed up!

**Comment by taylor-bsg** [comment]
Very nice!

**Pull request merged**
