### PR TITLE
Introduce compressed_support_p config parameter

### PR DESCRIPTION
**Pull request by WasabiFan**
Currently unused and defaults to disabled.

Looking for this to go in before the main PR.

Precursor to #1098.

### CODE REVIEW

**Comment by WasabiFan** [comment]
Swapped it to enabled by default because it looks like the ROM tests have default values hard-coded.

**Comment by dpetrisko** [comment]
Can we add 
```
typedef logic [1:0]
{
  e_misaligned_instr_support
  ,e_misaligned_data_support
  ,e_compressed_instr_support
} bp_compressed_support_e
```

Defaulting to (1 << e_misaligned_instr_support) is fine. We can disable the aviary test in CI for now, we'll just put a TODO: to fix before merging FE->DEV. Still not sure what the overhead is here and if having this as default is fine

**Comment by WasabiFan** [comment]
What would `e_misaligned_data_support` do?

**Comment by WasabiFan** [comment]
Oh, also, this would imply you can select multiple variants at once. Is that really desirable? It seems to me that supporting three options -- none, misaligned, compressed -- would model the available configurations better.

**Comment by dpetrisko** [comment]
Misaligned data would be D$ which supports misaligned accesses (required for some hypervisor implementations). 

I think that answers the other question, which is that we may support I$ vs D$ alignment independently in an RV64IAZamisalignedatomics configuration. But you're right that support will likely be monotonic I$ -> C -> D$ in practice

**Comment by WasabiFan** [comment]
I think the thing I'm missing is why the "compressed_support" config parameter affects D$ alignment. Wouldn't the D$ alignment be a toggle independent of the compressed instruction support level? They seem unrelated.

**Comment by dpetrisko** [comment]
Yeah, I guess "alignment support" is probably more what I'm going for, and is orthogonal. You know, let's shelve this until the rest of the support is there anyway

**Pull request merged**
