### PR TITLE
Fixes L2 hashing problem

### LINKED ISSUE #910: Reduce L2 tag width based on hash
## Area
bp_me_cce_to_cache, bsg_cache, memory system

## Current behavior
Currently, we send the entire address to the L2 cache. However, because we have already hashed to distribute to the L2s, this is unnecessary. 

## Desired behavior
We can trim the lower tag bits and re-append them at the DRAM interface (this must be kept in sync with the hashing algorithm).

## Proposed solution
Modify the bp_me_cce_to_cache adapter and instantiate a smaller bsg_cache. Also need to modify the test dram interface to interact with the cache ids, so that addresses are correctly reassembled.

## Analysis
Mild reduction in tag size (lg_num_cores), wire reduction in dma packet, no impact on wormhole size because data > header for that interface. Small buffer removal.

## Verification
Standard regression, paying particular attention to non-zero / large numbers of cores.

## Additional context
Need to update downstream tapeout repos to generate the correct memories

### PR DESCRIPTION
**Pull request by dpetrisko**
## Issue Fixed
#910 , context and justification there

## Area
bsg_cache_to_axi, test memory system

## Additional Changes Required (if any)
Changes to bsg_fpga, width of L2 cache tag RAMs

## Verification
Standard regression

### CODE REVIEW

**Review by taylor-bsg — COMMENTED** [review]
How about a regression test to check for this bug in the future?

**Comment by dpetrisko** [comment]
Not sure how, it’s invisible to software

**Comment by dpetrisko** [comment]
I suppose we could have a hardware monitor check for cache misses

**Comment by taylor-bsg** [comment]
Yep, or a bind statement

**Pull request merged**
