### PR TITLE
CCE v3 architecture update

### PR DESCRIPTION
**Pull request by muwyse**
This change updates the CCE architecture. The main updates are separating instruction fetch from decoded+execute to break a critical path (Issue #293 ) and re-designing the coherence directory to support different I$, D$, and accelerator $ organizations.

ME tests are cleaned up, working, and added back to regressions.

### CODE REVIEW

**Comment by dpetrisko** [comment]
This is super beefy.  I'll look through for style things, but I think I'll have to trust you for architecture changes.

Few high level questions:

>The main updates are separating instruction fetch from decoded+execute to break a critical path (Issue #293 ) 

Nice! Will run this through the backend.  Are there performance (IPC) implications?

>re-designing the coherence directory to support different I$, D$, and accelerator $ organizations.

We should probably have a test configuration for hetero cache-configs.  (Although you might need @Shashank-Vijay @sripathi-muralitharan changes to have the caches actually change size correctly)

34 bit instructions are good from an area perspective.  Could you post a list of the most crowded instruction encodings? Of course, the dream is #378, but that may not be realistic without 48 bit extensions for bedrock instructions.

**Comment by muwyse** [comment]
> Are there performance (IPC) implications?
Likely, yes. There is a static branch prediction bit (that can be specified as predict taken / not taken by the ucode programmer). If the prediction is correct there is no penalty. Mispredict is a 1 cycle penalty.

> We should probably have a test configuration for hetero cache-configs
Yes, this will definitely require their changes. I only added the CCE support.

> 34 bit instructions are good from an area perspective. Could you post a list of the most crowded instruction encodings? Of course, the dream is #378, but that may not be realistic without 48 bit extensions for bedrock instructions.
I will cleanup the docs I have and upload. I think the tightest encodings are the special branch flag ops, push queue ops, and directory read/write ops. I still need to investigate RV64E to see what could be done with it.

**Comment by dpetrisko** [comment]
>I will cleanup the docs I have and upload. I think the tightest encodings are the special branch flag ops, push queue ops, and directory read/write ops. I still need to investigate RV64E to see what could be done with it.

I'm definitely not going to hold this PR up for it, but 32 bits would be nice for 
- eventual RV64E
- Byte-sized RAMs are often easier/more efficient to generate from a CAD tool perspective

We can discuss once the docs are up, but some ideas to loosen up bits would be:
1) fewer GPRs (not sure how many you use now)
2) incomplete branch target space (say, +-32 instead of full range, fairly common for embedded code)
3) Move queue selection partially into opcode space.

Another way to handle it is to have longer instructions for CCE-special extensions.  i.e. 48 bit instructions, which are supported by the RV64E isa.  The downsides to this are the wider RAM and slightly more complicated fetch logic.

**Comment by muwyse** [comment]
Regressions passed: https://gitlab.com/black-parrot/black-parrot/pipelines/131515979

I also verified the FSM CCE is up to date and working so @sripathi-muralitharan and @Shashank-Vijay can use it for their work.

**Comment by dpetrisko** [comment]
LGTM!

**Pull request merged**
